version: '3'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - PEERS=backend2:3000,backend3:3000
    ports:
      - "3001:3000" 

  backend2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - PEERS=backend2:3000,backend3:3000
    ports:
      - "3002:3000" 

  backend3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=3000
      - PEERS=backend2:3000,backend3:3000
    ports:
      - "3003:3000" 
  